### ISSUE TITLE
List the organization's private repositories

### ISSUE THREAD

**Issue by IanTorquato** [8LWXpg/PowerToysRun-GitHubRepo#3]
Is it possible to access my organization's private repositories?

I imagine something with "GitHub auth token", but I configured it here and it didn't list any repositories

**Comment by 8LWXpg** [comment]
The current API for user only lists public repos, it's needed to change API for default user.

does [this API](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-the-authenticated-user) lists your organization's private repos?

**Comment by IanTorquato** [comment]
I was able to list the repositories using a different access token: [Fine-grained personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token)
Before I had created a "Personal access token (classic)"

However, it only lists the specific repository if I search for its name without the organization at the beginning
Ex.:
✅ `repository-name`
✅ `reposit`
❌ `organization-name/repository-name`

Anyway, that's enough for me. **Thanks for the tip and the plugin** 😉

**Comment by 8LWXpg** [comment]
Also note that the settings in PowerToys is stored locally without encryption, so use at your own risk.
