### ISSUE TITLE
Open links in default browser

### ISSUE THREAD

**Issue by johurul-haque** [8LWXpg/PowerToysRun-GitHubRepo#5]
### Description

I'm using firefox as my default browser and plugin does not open links in firefox. Rather it opens the repository inside chrome.

### Use case

When opening a repository it should open my default browser.

**Comment by 8LWXpg** [comment]
I'm able to open in Firefox after making it as default browser and restarting PowerToys, maybe check your Windows settings?

**Comment by johurul-haque** [comment]
It's working now after restarting. 

When I installed the plugin chrome was my default browser. After changing it I completely forgot about restarting powertoys.

Thanks.
