### ISSUE TITLE
Search for private repositories

### ISSUE THREAD

**Issue by nicoryy** [8LWXpg/PowerToysRun-GitHubRepo#7]
### Description

I'de like to know if is possible to have an feature that allows to log-in and search for private repos. I struggle everey time that i do a git clone, i need to open github website, go to repos, find my repository and got the url. This addon will make it so much easier do that if that were possible.

**Comment by 8LWXpg** [comment]
Try setting up the [access token](https://github.com/8LWXpg/PowerToysRun-GitHubRepo?tab=readme-ov-file#settings) in settings.
